// Copyright (C) 2026 Abdul, Hashim.
//
// This file is part of CARLA Studio.
// Licensed under the GNU Affero General Public License v3 or later —
// see <LICENSE> at the project root or
// <https://www.gnu.org/licenses/agpl-3.0.html> for the full text.
// SPDX-License-Identifier: AGPL-3.0-or-later

#include "vehicle_import/KitBundler.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSaveFile>
#include <QTextStream>

namespace carla_studio::vehicle_import {

QString renderKitReadme(const VehicleSpec &spec) {
  QString out;
  QTextStream s(&out);
  s << "# Vehicle Kit — " << spec.name << "\n\n";
  s << "Auto-generated by CARLA Studio. This kit contains everything you need to "
       "import this vehicle into a CARLA source build, with all CARLA-specific "
       "rules (bone names, physics damping, kinematic wheels, size-class presets) "
       "already encoded.\n\n";
  s << "## Files\n\n";
  s << "- `mesh.<ext>` — your source mesh (un-modified for now; Studio will canonicalize "
       "in slice 3).\n";
  s << "- `spec.json` — full canonical spec used by the UE plugin in Full mode. "
       "Every value below is derived from the mesh, no user inputs required.\n";
  s << "- `VehicleParameters.entry.json` — paste-ready JSON entry for "
       "`Content/Carla/Config/VehicleParameters.json` in your CARLA tree.\n";
  s << "- `README.md` — this file.\n\n";
  s << "## Detected vehicle profile\n\n";
  s << "| Field | Value |\n|---|---|\n";
  s << "| Name | `" << spec.name << "` |\n";
  s << "| Size class | `" << sizeClassName(spec.sizeClass) << "` |\n";
  s << "| Mass | " << QString::number(spec.mass, 'f', 0) << " kg |\n";
  s << "| Suspension damping | " << QString::number(spec.suspDamping, 'f', 2) << " |\n";
  s << "| Torque-curve preset | `" << spec.torqueCurveTag << "` |\n";
  s << "| Chassis bbox (cm) | "
    << QString("X[%1..%2] Y[%3..%4] Z[%5..%6]")
         .arg(spec.chassisXMin, 0, 'f', 1).arg(spec.chassisXMax, 0, 'f', 1)
         .arg(spec.chassisYMin, 0, 'f', 1).arg(spec.chassisYMax, 0, 'f', 1)
         .arg(spec.chassisZMin, 0, 'f', 1).arg(spec.chassisZMax, 0, 'f', 1)
    << " |\n";
  s << "| Four-wheeled | " << (spec.hasFourWheels ? "yes" : "no") << " |\n";
  if (spec.smallVehicleNeedsWheelShape)
    s << "| Note | wheel radius < 18 cm — Chaos vehicle physics needs a custom "
         "smaller `WheelShape` static mesh; the importer applies one automatically. |\n";
  s << "\n## Per-wheel measurements (cm, Unreal units)\n\n";
  s << "| Wheel | X | Y | Z | Radius | Width |\n|---|---|---|---|---|---|\n";
  static const char *names[4] = {"Front-Left", "Front-Right", "Rear-Left", "Rear-Right"};
  for (int i = 0; i < 4; ++i) {
    const WheelSpec &w = spec.wheels[i];
    s << "| " << names[i] << " | "
      << QString::number(w.x, 'f', 1) << " | "
      << QString::number(w.y, 'f', 1) << " | "
      << QString::number(w.z, 'f', 1) << " | "
      << QString::number(w.radius, 'f', 1) << " | "
      << QString::number(w.width, 'f', 1) << " |\n";
  }
  return out;
}

namespace {

QJsonObject vehicleParametersEntry(const VehicleSpec &spec) {
  QJsonObject e;
  e["Make"]              = QStringLiteral("Custom");
  e["Model"]             = spec.name;
  e["Class"] = QStringLiteral("/Game/Carla/Static/Vehicles/4Wheeled/") + spec.name +
               QStringLiteral("/BP_") + spec.name +
               QStringLiteral(".BP_") + spec.name + QStringLiteral("_C");
  e["NumberOfWheels"]    = 4;
  e["Generation"]        = 2;
  e["ObjectType"]        = QString();
  e["BaseType"]          = QStringLiteral("car");
  e["SpecialType"]       = QString();
  e["HasDynamicDoors"]   = false;
  e["HasLights"]         = false;
  e["RecommendedColors"] = QJsonArray();
  e["SupportedDrivers"]  = QJsonArray();
  return e;
}

bool writeText(const QString &path, const QString &text, KitBundleResult *r) {
  QSaveFile f(path);
  if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
    if (r) r->detail = QStringLiteral("Cannot write %1").arg(path);
    return false;
  }
  f.write(text.toUtf8());
  if (!f.commit()) {
    if (r) r->detail = QStringLiteral("Failed to commit %1").arg(path);
    return false;
  }
  if (r) r->writtenFiles << path;
  return true;
}

}  // namespace

KitBundleResult writeVehicleKit(const VehicleSpec &spec, const QString &outputDir) {
  KitBundleResult r;
  r.outputDir = outputDir;
  if (spec.name.isEmpty()) { r.detail = "Spec has no name."; return r; }
  if (!QDir().mkpath(outputDir)) { r.detail = "Cannot mkpath " + outputDir; return r; }

  const QString readme = renderKitReadme(spec);
  if (!writeText(outputDir + "/README.md", readme, &r)) return r;

  const QJsonObject specJson = specToJson(spec);
  if (!writeText(outputDir + "/spec.json",
                 QString::fromUtf8(QJsonDocument(specJson).toJson(QJsonDocument::Indented)),
                 &r)) return r;

  QJsonObject entryWrapper;
  QJsonArray vehicles;
  vehicles.append(vehicleParametersEntry(spec));
  entryWrapper["Vehicles"] = vehicles;
  if (!writeText(outputDir + "/VehicleParameters.entry.json",
                 QString::fromUtf8(QJsonDocument(entryWrapper).toJson(QJsonDocument::Indented)),
                 &r)) return r;

  if (!spec.meshPath.isEmpty() && QFileInfo(spec.meshPath).isFile()) {
    const QString ext = QFileInfo(spec.meshPath).suffix().toLower();
    const QString dst = outputDir + "/mesh." + ext;
    QFile::remove(dst);
    if (QFile::copy(spec.meshPath, dst)) r.writtenFiles << dst;
  }

  r.ok = true;
  r.detail = QStringLiteral("Wrote %1 files to %2").arg(r.writtenFiles.size()).arg(outputDir);
  return r;
}

}  // namespace carla_studio::vehicle_import
